Repository RafaelTurra/devops-aula07, pull requests merged in 2018-03, with the labels that each got.

#2 Integrar requisitos v1.0
  docs/requisitos.md
Labels: análise

#5 Integrar arquitetura v1.0
  docs/arquitetura.md
Labels: arquitetura

#8 Create homologacao.md
  docs/homologacao.md
Labels: Homologação

#10 V1.0 programacao
  src/jogovelha.py
Labels: programação

#13 V1.0
  docs/arquitetura.md
  docs/homologacao.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações

#20 V.1.2 analise
  docs/arquitetura.md
  docs/homologacao.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: análise

#23 V.1.2 arquitetura
  arquiterura.md
  docs/análise.md
Labels: arquitetura

#22 V.1.2 programacao
  docs/programacao.md
  docs/testes.md
Labels: programação
